### ISSUE TITLE
Support for Z3 [Feature Request]

### ISSUE THREAD

**Issue by BoBeR182** [itandy/XperiaAOSPNavBarButtons#3]
I have a Sony Xperia Z3 D6603, running https://forum.xda-developers.com/z3/development/rom-existenz-marshmallow-v1-0-0-29-04-t3368343 With a locked bootloader. Currently installing this Xposed module results in a crash loop of SystemUI.

What debug information do you need to help assist?

**Comment by itandy** [comment]
Sorry that eXistenZ ROM, similar to CM, has its own implementation of the
navbar. That's why this module won't work on it.

Andy Wong

email: andy@gzplanet.com

**Comment by BoBeR182** [comment]
Sucks to suck.
